from __future__ import annotations

from pathlib import Path


def run(input_dir: str, output_dir: str) -> None:
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    print("CRM Task (Community Marketing) Starting...")
    print(f"   Input: {input_dir}")
    print(f"   Output: {output_dir}")

    deliverables = {
        "community-strategy.md": _community_strategy(),
        "channel-architecture.md": _channel_architecture(),
        "new-member-journey.md": _new_member_journey(),
        "community-ritual-calendar.md": _ritual_calendar(),
        "ambassador-program-brief.md": _ambassador_program(),
        "community-health-audit.md": _health_audit(),
    }

    for filename, content in deliverables.items():
        filepath = output_path / filename
        filepath.write_text(content)
        print(f"   Written: {filename}")

    print("\nCRM Task Complete!")
    print(f"   Output directory: {output_path}")


def _community_strategy() -> str:
    return """# Community Strategy

## Foundation

### Primary Community Goals
Choose your primary focus:
- [ ] Retention — Keep existing users engaged and active
- [ ] Activation — Help users reach time-to-value faster
- [ ] Word-of-mouth — Drive referrals and organic growth
- [ ] Support deflection — Let community help users solve problems
- [ ] Product feedback — Get direct input on features and roadmap
- [ ] Revenue — Drive upgrades and expansions through community

## Platform Selection

| Platform | Best For | Watch Out For |
|----------|----------|---------------|
| Discord | Developer, gaming, creator communities | High noise, hard to search |
| Slack | B2B / professional communities | Free tier limits history |
| Circle | Creator or course-based communities | Less organic discovery |
| Reddit | High-volume public communities | You don't own it |
| Forum (Discourse) | Long-form technical communities | Slower velocity |

## 90-Day Launch Plan

### Days 1-30: Foundation
- [ ] Recruit 20-50 founding members manually
- [ ] Write community guidelines that describe the vibe
- [ ] Pre-populate channels with 5-10 seed posts
- [ ] Reply to every post personally
- [ ] Welcome every new member by name

### Days 31-60: Activity
- [ ] Host first weekly call or AMA
- [ ] Launch recurring community ritual
- [ ] Identify first power users
- [ ] Set up community health metrics tracking

### Days 61-90: Scale
- [ ] Open to public with clear onboarding
- [ ] Launch ambassador program
- [ ] Showcase first member wins publicly
- [ ] Plan next 90 days based on learnings

---

*Generated by Revenue Manager - CRM Task*
"""


def _channel_architecture() -> str:
    return """# Channel Architecture

## Channel Categories and Purpose

### Welcome & Onboarding
| Channel | Purpose | Guidelines |
|---------|---------|------------|
| #welcome | New member introductions | Post brief intro |
| #rules-guidelines | Community guidelines | Read-only |
| #start-here | Onboarding resources | Read-only |

### Core Discussion
| Channel | Purpose | Guidelines |
|---------|---------|------------|
| #general | Main conversation hub | Keep on-topic |
| #help-support | Member-to-member support | Be helpful |

### Show & Tell
| Channel | Purpose | Guidelines |
|---------|---------|------------|
| #show-and-tell | Member projects | Celebrate others |
| #case-studies | Success stories | Include metrics |

### Announcements
| Channel | Purpose | Guidelines |
|---------|---------|------------|
| #announcements | Official updates | Read-only |
| #product-updates | Product changes | Read-only |

## Moderation Guidelines

**Do:**
- Be welcoming to new members
- Upvote helpful answers
- Use threads to keep channels organized

**Don't:**
- Spam self-promotion
- Derail discussions
- Argue personally

---

*Generated by Revenue Manager - CRM Task*
"""


def _new_member_journey() -> str:
    return """# New Member Journey

## Welcome Sequence

### Day 0: Join Instant
**Trigger:** Member joins community

**Actions:**
1. Auto-post in #welcome channel
2. Send welcome DM
3. Add member to New Members tag

### Day 1: First Day
**Actions:**
1. Check if member introduced themselves
2. Reply to first post within 2 hours

### Day 3: First Week Check-in
**Actions:**
1. Send check-in DM
2. Invite to upcoming event

### Day 7: First Week Review
**Actions:**
1. Review engagement metrics
2. Send personalized message
3. Add to appropriate segment

## First-Week Prompts
- Day 1: What brought you to [community]?
- Day 3: What are you currently working on?
- Day 5: What's your biggest challenge right now?
- Day 7: What would you like to get out of the community?

---

*Generated by Revenue Manager - CRM Task*
"""


def _ritual_calendar() -> str:
    return """# Community Ritual Calendar

## Weekly Rituals

### Monday: What Are You Working On?
**Purpose:** Share current projects, get feedback, build accountability

### Wednesday: Show and Tell
**Purpose:** Celebrate member wins and projects

### Friday: Wins and Learnings
**Purpose:** End-of-week wrap-up, share successes and lessons

## Monthly Rituals

### First Week: AMA with Expert/Founder
**Format:** 60-minute Q&A session, recorded

### Second Week: Office Hours
**Format:** Drop-in 2-hour block

### Third Week: Workshop / Tutorial
**Format:** 45-minute presentation + 15-minute Q&A

### Fourth Week: Member Spotlight
**Format:** Interview post or video

## Engagement Boosters

| Trigger | Action |
|---------|--------|
| Member hits 10 posts | Send congratulatory DM + badge |
| Member hits 50 posts | Feature in Member Spotlight |
| 30-day inactive member | Personal check-in DM |
| New member first post | Team reply within 2 hours |

---

*Generated by Revenue Manager - CRM Task*
"""


def _ambassador_program() -> str:
    return """# Ambassador Program Brief

## Candidate Identification

Look for people who:
- Already recommend you unprompted
- Are highly active in the community
- Have influence in their network
- Align with your brand values
- Create quality content about your product

## Benefits Package

### Exclusive Access
- [ ] Early access to new features and products
- [ ] Direct line to product team for feedback
- [ ] Beta testing opportunities

### Recognition
- [ ] Public acknowledgment on website/social media
- [ ] Badges/credentials in community

### Materials & Tools
- [ ] Referral links and tracking dashboard
- [ ] Shareable assets (graphics, copy, templates)
- [ ] Private ambassador channel
- [ ] Monthly ambassador newsletter

## Ambassador Activities

| Activity | Frequency | Effort |
|----------|-----------|--------|
| Community support | As needed | 1-2 hrs/week |
| Content creation | 1-2x/month | 2-4 hrs |
| Event participation | 1-4x/quarter | 2-4 hrs |
| Product feedback | Monthly | 1 hr |
| Referrals | Ongoing | Variable |

---

*Generated by Revenue Manager - CRM Task*
"""


def _health_audit() -> str:
    return """# Community Health Audit

## Key Metrics

### Stickiness
**DAU/MAU Ratio:** [XX]%
- [ ] Above 20% — OK
- [ ] Below 20% — Warning

### New Member Engagement
**% of new members who post within 7 days:** [XX]%
- [ ] Above 50% — OK
- [ ] Below 50% — Warning

### Thread Engagement
**% of posts that receive at least one reply:** [XX]%
- [ ] Above 60% — OK
- [ ] Below 60% — Warning

### Churn / Lurker Ratio
**% of members who joined but haven't posted in 30+ days:** [XX]%
- [ ] Below 40% — OK
- [ ] Above 40% — Warning

## Warning Signs Checklist

- [ ] Most posts are from the company team, not members
- [ ] Questions go unanswered for >24 hours
- [ ] The same 5 people account for 80%+ of engagement
- [ ] New members stop posting after their intro message
- [ ] Member growth is slowing without engagement increase

## Health Monitoring

Track these metrics weekly:
- DAU/MAU ratio
- New member post rate (7-day)
- Thread reply rate
- Churn/lurker ratio
- Content from non-staff (%)

---

*Generated by Revenue Manager - CRM Task*
"""
