from __future__ import annotations

from pathlib import Path


def run(input_dir: str, output_dir: str) -> None:
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    print("RevOps Task Starting...")
    print(f"   Input: {input_dir}")
    print(f"   Output: {output_dir}")

    deliverables = {
        "lifecycle-stage-definitions.md": _lifecycle_definitions(),
        "scoring-specification.md": _scoring_spec(),
        "routing-rules.md": _routing_rules(),
        "pipeline-configuration.md": _pipeline_config(),
        "metrics-dashboard-spec.md": _metrics_dashboard(),
    }

    for filename, content in deliverables.items():
        filepath = output_path / filename
        filepath.write_text(content)
        print(f"   Written: {filename}")

    print("\nRevOps Task Complete!")
    print(f"   Output directory: {output_path}")


def _lifecycle_definitions() -> str:
    return """# Lifecycle Stage Definitions

## Stage Definitions

| Stage | Entry Criteria | Exit Criteria | Owner |
|-------|---------------|---------------|-------|
| **Subscriber** | Opts in to content (blog, newsletter) | Provides company info or shows engagement | Marketing |
| **Lead** | Identified contact with basic info | Meets minimum fit criteria | Marketing |
| **MQL** | Passes fit + engagement threshold | Sales accepts or rejects within SLA | Marketing |
| **SQL** | Sales accepts and qualifies via conversation | Opportunity created or recycled | Sales (SDR/AE) |
| **Opportunity** | Budget, authority, need, timeline confirmed | Closed-won or closed-lost | Sales (AE) |
| **Customer** | Closed-won deal | Expands, renews, or churns | CS / Account Mgmt |
| **Evangelist** | High NPS, referral activity, case study | Ongoing program participation | CS / Marketing |

## MQL Definition

An MQL requires both **fit** and **engagement**:

- **Fit score** — Does this person match your ICP? (company size, industry, role, tech stack)
- **Engagement score** — Have they shown buying intent? (pricing page, demo request, multiple visits)

Neither alone is sufficient. A perfect-fit company that never engages isn't an MQL. A student downloading every ebook isn't an MQL.

## MQL-to-SQL Handoff SLA

- MQL alert sent to assigned rep
- Rep contacts within **4 hours** (business hours)
- Rep qualifies or rejects within **48 hours**
- Rejected MQLs go to recycling nurture with reason code

---

*Generated by Revenue Manager - RevOps Task*
"""


def _scoring_spec() -> str:
    return """# Scoring Specification

## Scoring Dimensions

### Explicit Scoring (Fit) — Who They Are
- Company size, industry, revenue
- Job title, seniority, department
- Tech stack, geography

### Implicit Scoring (Engagement) — What They Do
- Page visits (especially pricing, demo, case studies)
- Content downloads, webinar attendance
- Email engagement (opens, clicks)
- Product usage (for PLG)

### Negative Scoring — Disqualifying Signals
- Competitor email domains
- Student/personal email
- Unsubscribes, spam complaints
- Job title mismatches (intern, student)

## Scoring Model Template

| Attribute | Type | Points |
|-----------|------|--------|
| **Fit Attributes** | | |
| Company size 10-50 employees | Explicit | +10 |
| Company size 51-200 employees | Explicit | +15 |
| Company size 200+ employees | Explicit | +20 |
| Job title: Executive | Explicit | +20 |
| Job title: Manager | Explicit | +10 |
| Job title: Individual Contributor | Explicit | +5 |
| Target industry match | Explicit | +10 |
| **Engagement Attributes** | | |
| Visited pricing page | Implicit | +15 |
| Requested demo | Implicit | +25 |
| Downloaded case study | Implicit | +10 |
| Attended webinar | Implicit | +15 |
| Email open (any) | Implicit | +2 |
| Email click (any) | Implicit | +5 |
| Product sign-up | Implicit | +20 |
| **Negative Attributes** | | |
| Competitor domain | Negative | -50 |
| Personal email (gmail, yahoo) | Negative | -10 |
| Student/university email | Negative | -20 |

## MQL Threshold

**Target: 75 points**

Leads scoring 75+ points are automatically flagged as MQLs and routed to sales.

---

*Generated by Revenue Manager - RevOps Task*
"""


def _routing_rules() -> str:
    return """# Routing Rules

## Routing Methods

| Method | How It Works | Best For |
|--------|-------------|----------|
| **Round-robin** | Distribute evenly across reps | Equal territories, similar deal sizes |
| **Territory-based** | Assign by geography, vertical, or segment | Regional teams, industry specialists |
| **Account-based** | Named accounts go to named reps | ABM motions, strategic accounts |
| **Skill-based** | Route by deal complexity, product line, or language | Diverse product lines, global teams |

## Speed-to-Lead

Response time is the single biggest factor in lead conversion:
- Contact within **5 minutes** = 21x more likely to qualify
- After **30 minutes**, conversion drops by 10x
- After **24 hours**, the lead is effectively cold

## Routing Decision Tree

```
New MQL Received
  |
  v
Is this a named account?
  |
  +-- YES --> Named Account Rep
  |
  +-- NO --> Is geography in territory?
             |
             +-- YES --> Territory Rep
             |
             +-- NO --> Round-robin Fallback
```

---

*Generated by Revenue Manager - RevOps Task*
"""


def _pipeline_config() -> str:
    return """# Pipeline Configuration

## Pipeline Stages

| Stage | Required Fields | Exit Criteria |
|-------|----------------|---------------|
| **Qualified** | Contact info, company, source, fit score | Discovery call scheduled |
| **Discovery** | Pain points, current solution, timeline | Needs confirmed, demo scheduled |
| **Demo/Evaluation** | Technical requirements, decision makers | Positive evaluation, proposal requested |
| **Proposal** | Pricing, terms, stakeholder map | Proposal delivered and reviewed |
| **Negotiation** | Redlines, approval chain, close date | Terms agreed, contract sent |
| **Closed Won** | Signed contract, payment terms | Handoff to CS complete |
| **Closed Lost** | Loss reason, competitor (if any) | Post-mortem logged |

## Stage Hygiene

- **Required fields per stage** — Don't let reps advance a deal without filling in required data
- **Stale deal alerts** — Flag deals that sit in a stage beyond 2x average days
- **Stage skip detection** — Alert when deals jump stages
- **Close date discipline** — Push dates must include a reason

## Automation Triggers

### Lifecycle Stage Updates
- Auto-advance stages when criteria are met
- Require field validation before stage change

### Task Creation on Handoff
- Create follow-up task when MQL assigned to rep
- Set SLA deadline based on stage requirements

### SLA Alerts
- Notify manager if rep misses response time SLA
- Escalate to team lead after 24h overdue

---

*Generated by Revenue Manager - RevOps Task*
"""


def _metrics_dashboard() -> str:
    return """# Metrics Dashboard Specification

## Key Metrics

| Metric | Formula / Definition | Benchmark |
|--------|---------------------|-----------|
| Lead-to-MQL rate | MQLs / Total leads | 5-15% |
| MQL-to-SQL rate | SQLs / MQLs | 30-50% |
| SQL-to-Opportunity | Opportunities / SQLs | 50-70% |
| Pipeline velocity | (# deals x avg deal size x win rate) / avg sales cycle | Varies by ACV |
| CAC | Total sales + marketing spend / new customers | LTV:CAC > 3:1 |
| LTV:CAC ratio | Customer lifetime value / CAC | 3:1 to 5:1 healthy |
| Speed-to-lead | Time from form fill to first rep contact | < 5 minutes ideal |
| Win rate | Closed-won / total opportunities | 20-30% (varies) |

## Dashboard Structure

### Marketing View
- Lead volume
- MQL rate
- Source attribution
- Cost per MQL

### Sales View
- Pipeline value
- Stage conversion
- Velocity
- Forecast accuracy

### Executive View
- CAC
- LTV:CAC
- Revenue vs. target
- Pipeline coverage

## Refresh Cadence

| View | Frequency |
|------|-----------|
| Marketing View | Daily |
| Sales View | Daily |
| Executive View | Weekly |

---

*Generated by Revenue Manager - RevOps Task*
"""
