#!/usr/bin/env node
/**
 * RevOps Task - Revenue Operations
 * 
 * Source: marketingskills/revops
 * 
 * Handles: lead lifecycle management, scoring, routing, pipeline stages,
 *          MQL/SQL definitions, marketing-to-sales handoff processes
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { HubSpot } from '../../../_providers/marketing/hubspot.mjs';
import { Salesforce } from '../../../_providers/marketing/salesforce.mjs';
import { Close } from '../../../_providers/marketing/close.mjs';
import { Outreach } from '../../../_providers/marketing/outreach.mjs';
import { Crossbeam } from '../../../_providers/marketing/crossbeam.mjs';
import { Apollo } from '../../../_providers/marketing/apollo.mjs';
import { Clearbit } from '../../../_providers/marketing/clearbit.mjs';
import { ZoomInfo } from '../../../_providers/marketing/zoominfo.mjs';
import { Clay } from '../../../_providers/marketing/clay.mjs';
import { Segment } from '../../../_providers/marketing/segment.mjs';

/**
 * Revenue operations task
 * @param {Object} config - Task configuration
 */
export async function revopsTask(config) {
  const { input_dir, output_dir, device } = config;
  
  console.log('🔄 RevOps Task Starting...');
  console.log(`   Input: ${input_dir}`);
  console.log(`   Output: ${output_dir}`);
  console.log(`   Device: ${device}`);

  const outputPath = join(process.cwd(), output_dir);
  
  // Ensure output directory exists
  mkdirSync(outputPath, { recursive: true });

  // Generate RevOps deliverables
  const deliverables = {
    'lifecycle-stage-definitions.md': generateLifecycleDefinitions(),
    'scoring-specification.md': generateScoringSpec(),
    'routing-rules.md': generateRoutingRules(),
    'pipeline-configuration.md': generatePipelineConfig(),
    'metrics-dashboard-spec.md': generateMetricsDashboard(),
  };

  // Write deliverables
  for (const [filename, content] of Object.entries(deliverables)) {
    const filepath = join(outputPath, filename);
    writeFileSync(filepath, content);
    console.log(`   ✓ Written: ${filename}`);
  }

  console.log('\n✅ RevOps Task Complete!');
  console.log(`   Output directory: ${outputPath}`);
  console.log('\nDeliverables:');
  console.log('  - lifecycle-stage-definitions.md');
  console.log('  - scoring-specification.md');
  console.log('  - routing-rules.md');
  console.log('  - pipeline-configuration.md');
  console.log('  - metrics-dashboard-spec.md');
}

/**
 * Generate lifecycle stage definitions document
 */
function generateLifecycleDefinitions() {
  return `# Lifecycle Stage Definitions

## Stage Definitions

| Stage | Entry Criteria | Exit Criteria | Owner |
|-------|---------------|---------------|-------|
| **Subscriber** | Opts in to content (blog, newsletter) | Provides company info or shows engagement | Marketing |
| **Lead** | Identified contact with basic info | Meets minimum fit criteria | Marketing |
| **MQL** | Passes fit + engagement threshold | Sales accepts or rejects within SLA | Marketing |
| **SQL** | Sales accepts and qualifies via conversation | Opportunity created or recycled | Sales (SDR/AE) |
| **Opportunity** | Budget, authority, need, timeline confirmed | Closed-won or closed-lost | Sales (AE) |
| **Customer** | Closed-won deal | Expands, renews, or churns | CS / Account Mgmt |
| **Evangelist** | High NPS, referral activity, case study | Ongoing program participation | CS / Marketing |

## MQL Definition

An MQL requires both **fit** and **engagement**:

- **Fit score** — Does this person match your ICP? (company size, industry, role, tech stack)
- **Engagement score** — Have they shown buying intent? (pricing page, demo request, multiple visits)

Neither alone is sufficient. A perfect-fit company that never engages isn't an MQL. A student downloading every ebook isn't an MQL.

## MQL-to-SQL Handoff SLA

Define response times and document them:
- MQL alert sent to assigned rep
- Rep contacts within **4 hours** (business hours)
- Rep qualifies or rejects within **48 hours**
- Rejected MQLs go to recycling nurture with reason code

---

*Generated by Revenue Manager - RevOps Task*
`;
}

/**
 * Generate scoring specification document
 */
function generateScoringSpec() {
  return `# Scoring Specification

## Scoring Dimensions

### Explicit Scoring (Fit) — Who They Are
- Company size, industry, revenue
- Job title, seniority, department
- Tech stack, geography

### Implicit Scoring (Engagement) — What They Do
- Page visits (especially pricing, demo, case studies)
- Content downloads, webinar attendance
- Email engagement (opens, clicks)
- Product usage (for PLG)

### Negative Scoring — Disqualifying Signals
- Competitor email domains
- Student/personal email
- Unsubscribes, spam complaints
- Job title mismatches (intern, student)

## Building a Scoring Model

1. Define your ICP attributes and weight them
2. Identify high-intent behavioral signals from closed-won data
3. Set point values for each attribute and behavior
4. Set MQL threshold (typically 50-80 points on a 100-point scale)
5. Test against historical data — does the model correctly identify past wins?
6. Launch, measure, and recalibrate quarterly

## Scoring Model Template

| Attribute | Type | Points |
|-----------|------|--------|
| **Fit Attributes** | | |
| Company size 10-50 employees | Explicit | +10 |
| Company size 51-200 employees | Explicit | +15 |
| Company size 200+ employees | Explicit | +20 |
| Job title: Executive | Explicit | +20 |
| Job title: Manager | Explicit | +10 |
| Job title: Individual Contributor | Explicit | +5 |
| Target industry match | Explicit | +10 |
| **Engagement Attributes** | | |
| Visited pricing page | Implicit | +15 |
| Requested demo | Implicit | +25 |
| Downloaded case study | Implicit | +10 |
| Attended webinar | Implicit | +15 |
| Email open (any) | Implicit | +2 |
| Email click (any) | Implicit | +5 |
| Product sign-up | Implicit | +20 |
| **Negative Attributes** | | |
| Competitor domain | Negative | -50 |
| Personal email (gmail, yahoo) | Negative | -10 |
| Student/university email | Negative | -20 |

## MQL Threshold

**Target: 75 points**

Leads scoring 75+ points are automatically flagged as MQLs and routed to sales.

---

*Generated by Revenue Manager - RevOps Task*
`;
}

/**
 * Generate routing rules document
 */
function generateRoutingRules() {
  return `# Routing Rules

## Routing Methods

| Method | How It Works | Best For |
|--------|-------------|----------|
| **Round-robin** | Distribute evenly across reps | Equal territories, similar deal sizes |
| **Territory-based** | Assign by geography, vertical, or segment | Regional teams, industry specialists |
| **Account-based** | Named accounts go to named reps | ABM motions, strategic accounts |
| **Skill-based** | Route by deal complexity, product line, or language | Diverse product lines, global teams |

## Routing Rules Essentials

- Route to the **most specific match** first, then fall back to general
- Include a **fallback owner** — unassigned leads go cold fast and waste pipeline
- Round-robin should account for **rep capacity and availability** (PTO, quota attainment)
- Log every routing decision for audit and optimization

## Speed-to-Lead

Response time is the single biggest factor in lead conversion:
- Contact within **5 minutes** = 21x more likely to qualify (Lead Connect)
- After **30 minutes**, conversion drops by 10x
- After **24 hours**, the lead is effectively cold

Build routing rules that prioritize speed. Alert reps immediately. Escalate if SLA is missed.

## Routing Decision Tree

New MQL Received
  |
  v
Is this a named account?
  |
  +-- YES --> Named Account Rep
  |
  +-- NO --> Is geography in territory?
             |
             +-- YES --> Territory Rep
             |
             +-- NO --> Round-robin Fallback

## Platform-Specific Setup

### HubSpot
Use HubSpot workflows with assignment rules:
- Create workflow triggers on MQL lifecycle stage change
- Add enrollment conditions for territory/account matching
- Use "Wait" node for speed-to-lead SLA monitoring
- Create tasks for assigned reps with enrichment data

### Salesforce
Use Lead Assignment Rules:
- Create rule entry with MQL criteria
- Add rule entries for territory-based routing
- Set fallback assignment to queue or manager
- Use process builder for SLA alerts

---

*Generated by Revenue Manager - RevOps Task*
`;
}

/**
 * Generate pipeline configuration document
 */
function generatePipelineConfig() {
  return `# Pipeline Configuration

## Pipeline Stages

| Stage | Required Fields | Exit Criteria |
|-------|----------------|---------------|
| **Qualified** | Contact info, company, source, fit score | Discovery call scheduled |
| **Discovery** | Pain points, current solution, timeline | Needs confirmed, demo scheduled |
| **Demo/Evaluation** | Technical requirements, decision makers | Positive evaluation, proposal requested |
| **Proposal** | Pricing, terms, stakeholder map | Proposal delivered and reviewed |
| **Negotiation** | Redlines, approval chain, close date | Terms agreed, contract sent |
| **Closed Won** | Signed contract, payment terms | Handoff to CS complete |
| **Closed Lost** | Loss reason, competitor (if any) | Post-mortem logged |

## Stage Hygiene

- **Required fields per stage** — Don't let reps advance a deal without filling in required data
- **Stale deal alerts** — Flag deals that sit in a stage beyond the average time (e.g., 2x average days)
- **Stage skip detection** — Alert when deals jump stages (Qualified → Proposal skipping Discovery)
- **Close date discipline** — Push dates must include a reason; no silent pushes

## Stage Configuration for HubSpot

const pipelineStages = [
  {
    name: 'Qualified',
    requiredFields: ['contact_info', 'company', 'source', 'fit_score'],
    slaHours: 48
  },
  {
    name: 'Discovery',
    requiredFields: ['pain_points', 'current_solution', 'timeline'],
    slaHours: 72
  },
  {
    name: 'Demo/Evaluation',
    requiredFields: ['technical_requirements', 'decision_makers'],
    slaHours: 96
  },
  {
    name: 'Proposal',
    requiredFields: ['pricing', 'terms', 'stakeholder_map'],
    slaHours: 120
  },
  {
    name: 'Negotiation',
    requiredFields: ['redlines', 'approval_chain', 'close_date'],
    slaHours: 168
  },
  {
    name: 'Closed Won',
    requiredFields: ['signed_contract', 'payment_terms'],
    slaHours: null
  },
  {
    name: 'Closed Lost',
    requiredFields: ['loss_reason', 'competitor'],
    slaHours: null
  }
];

## Automation Triggers

### Lifecycle Stage Updates
- Auto-advance stages when criteria are met
- Require field validation before stage change

### Task Creation on Handoff
- Create follow-up task when MQL assigned to rep
- Set SLA deadline based on stage requirements

### SLA Alerts
- Notify manager if rep misses response time SLA
- Escalate to team lead after 24h overdue

### Deal Stage Triggers
- Auto-send proposals when stage changes to Proposal
- Update forecasts when stage changes to Negotiation
- Notify CS on Closed Won

---

*Generated by Revenue Manager - RevOps Task*
`;
}

/**
 * Generate metrics dashboard specification
 */
function generateMetricsDashboard() {
  return `# Metrics Dashboard Specification

## Key Metrics

| Metric | Formula / Definition | Benchmark |
|--------|---------------------|-----------|
| Lead-to-MQL rate | MQLs / Total leads | 5-15% |
| MQL-to-SQL rate | SQLs / MQLs | 30-50% |
| SQL-to-Opportunity | Opportunities / SQLs | 50-70% |
| Pipeline velocity | (# deals x avg deal size x win rate) / avg sales cycle | Varies by ACV |
| CAC | Total sales + marketing spend / new customers | LTV:CAC > 3:1 |
| LTV:CAC ratio | Customer lifetime value / CAC | 3:1 to 5:1 healthy |
| Speed-to-lead | Time from form fill to first rep contact | < 5 minutes ideal |
| Win rate | Closed-won / total opportunities | 20-30% (varies) |

## Dashboard Structure

### Marketing View
- Lead volume
- MQL rate
- Source attribution
- Cost per MQL

### Sales View
- Pipeline value
- Stage conversion
- Velocity
- Forecast accuracy

### Executive View
- CAC
- LTV:CAC
- Revenue vs. target
- Pipeline coverage

## Data Sources

| Metric | Primary Source | Secondary Source |
|--------|---------------|------------------|
| Lead volume | Marketing automation | CRM |
| MQL/SQL | CRM lifecycle stage | Marketing automation |
| Pipeline value | CRM opportunities | ERP |
| Win rate | CRM closed deals | ERP |
| CAC | Finance system | CRM/Marketing |
| LTV | Finance system | CRM |

## Refresh Cadence

| View | Frequency | Last Refresh |
|------|-----------|--------------|
| Marketing View | Daily | Auto |
| Sales View | Daily | Auto |
| Executive View | Weekly | Manual |

---

*Generated by Revenue Manager - RevOps Task*
`;
}

export default { revopsTask };
